version: "3.9"
   
services:
  web:
    build: .
    container_name: base_flask
    #command: flask --app main run -h 0.0.0.0 -p 5000
    #command: python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask --app main run -h 0.0.0.0 -p 5000
    command: python3 -m debugpy --listen 0.0.0.0:5678 -m flask --app main run -h 0.0.0.0 -p 5000
    
    volumes:
      - .:/code
    ports:
      - "5000:5000"
      - "5678:5678"