"""empty message

Revision ID: 50b7142963f9
Revises: 7fcfd5d54af6
Create Date: 2022-10-14 07:57:04.509097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b7142963f9'
down_revision = '7fcfd5d54af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('z')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('z', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
